# Generated by Django 5.2.7 on 2025-10-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
        ('pessoa', '0003_remove_professor_id_aluno_email_presidente_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='curso',
        ),
        migrations.AddField(
            model_name='aluno',
            name='cursos_matriculados',
            field=models.ManyToManyField(blank=True, related_name='alunos', to='curso.curso'),
        ),
    ]
