# Generated by Django 5.2.7 on 2025-10-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
        ('pessoa', '0004_remove_aluno_curso_aluno_cursos_matriculados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(db_column='CPF', max_length=11, unique=True)),
                ('tel', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(default='', max_length=50, unique=True)),
                ('is_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('is_superuser', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='presidente',
            old_name='is_admin',
            new_name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='presidente',
            name='id',
        ),
        migrations.AddField(
            model_name='presidente',
            name='id_presidente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cursos_matriculados',
            field=models.ManyToManyField(blank=True, related_name='alunos_matriculados', to='curso.curso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
