# Generated by Django 5.2.7 on 2025-10-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0006_remove_administrador_tel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='id_professor',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
