# Generated by Django 5.2.7 on 2025-11-13 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0008_alter_professor_id_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_nasc',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
