# Generated by Django 5.2.7 on 2025-11-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0010_alter_aluno_data_nasc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(db_column='CPF', max_length=11, unique=True)),
                ('tel', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(default='', max_length=50, unique=True)),
                ('id_doador', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
