# Generated by Django 5.2.7 on 2025-10-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0003_remove_professor_id_aluno_email_presidente_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nome_curso', models.CharField(default='', max_length=255)),
                ('professores', models.ManyToManyField(blank=True, related_name='curso_ministrado', to='pessoa.professor')),
            ],
        ),
    ]
