# Generated by Django 5.2.7 on 2025-10-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_remove_curso_id_curso_remove_curso_nome_curso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='id',
        ),
        migrations.AddField(
            model_name='curso',
            name='id_curso',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
