# Generated by Django 5.2.7 on 2025-10-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_remove_curso_id_curso_id_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeEsportiva',
            fields=[
                ('nome', models.CharField(default='', max_length=255)),
                ('id_ativesportiva', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='nome',
            field=models.CharField(default='', max_length=255),
        ),
    ]
