# Generated by Django 5.2.7 on 2025-10-31 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_alter_atividadeesportiva_id_professor_and_more'),
        ('pessoa', '0008_alter_professor_id_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadeesportiva',
            name='id_professor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='atividade_ministrado', to='pessoa.professor'),
        ),
    ]
