# Generated by Django 5.2.7 on 2025-10-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_atividadeesportiva_curso_nome'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='curso',
            table='Curso',
        ),
    ]
