# Generated by Django 5.2.7 on 2025-10-30 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_alter_curso_table'),
        ('pessoa', '0007_alter_professor_id_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeesportiva',
            name='id_professor',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='pessoa.professor'),
        ),
    ]
