# Generated by Django 5.2.6 on 2025-09-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taluno',
            name='atividades',
            field=models.ManyToManyField(related_name='alunos_atividades', to='educacao.tatividade_esportiva'),
        ),
        migrations.AddField(
            model_name='taluno',
            name='cursos',
            field=models.ManyToManyField(related_name='alunos', to='educacao.tcurso'),
        ),
    ]
