# Generated by Django 5.2.7 on 2025-10-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='data_nasc',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='id',
        ),
        migrations.RemoveField(
            model_name='presidente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='email',
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aluno',
            name='id_aluno',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(db_column='CPF', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='tel',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='presidente',
            name='cpf',
            field=models.CharField(db_column='CPF', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='presidente',
            name='tel',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cpf',
            field=models.CharField(db_column='CPF', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='tel',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
