# Generated by Django 5.2.7 on 2025-10-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_remove_aluno_data_nasc_remove_aluno_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='id',
        ),
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='presidente',
            name='email',
            field=models.EmailField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='presidente',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='id_professor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='id_aluno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='tel',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='presidente',
            name='tel',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='tel',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
