# Generated by Django 5.2.7 on 2025-10-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0005_administrador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='tel',
        ),
        migrations.AlterField(
            model_name='administrador',
            name='is_superuser',
            field=models.BooleanField(default=True, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='presidente',
            name='is_superuser',
            field=models.BooleanField(default=True, verbose_name='Presidente'),
        ),
    ]
