# Generated by Django 5.2.7 on 2025-10-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0007_alter_professor_id_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='id_professor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
