# Generated by Django 5.2.7 on 2025-11-13 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0009_aluno_data_nasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_nasc',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
