# Generated by Django 5.2.8 on 2025-11-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_horario'),
        ('pessoa', '0012_administrador_user_aluno_user_doador_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='atividades_matriculadas',
            field=models.ManyToManyField(blank=True, related_name='alunos_inscritos', to='curso.atividadeesportiva'),
        ),
    ]
