# Generated by Django 5.2.6 on 2025-09-26 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAtividade_esportiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('horario', models.CharField(max_length=50)),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_ministradas', to='pessoas.tprofessor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('horario', models.CharField(max_length=50)),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_ministrados', to='pessoas.tprofessor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
