# Generated by Django 5.2.7 on 2025-10-31 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
        ('pessoa', '0007_alter_professor_id_professor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='nome_curso',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='professores',
        ),
        migrations.CreateModel(
            name='AtividadeEsportiva',
            fields=[
                ('nome', models.CharField(default='', max_length=255)),
                ('id_ativesportiva', models.AutoField(primary_key=True, serialize=False)),
                ('id_professor', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='pessoa.professor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
