# Generated by Django 5.2.7 on 2025-10-31 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_rename_nome_curso_curso_nome_and_more'),
        ('pessoa', '0007_alter_professor_id_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='professores',
            field=models.ManyToManyField(blank=True, related_name='curso_ministrado', to='pessoa.professor'),
        ),
        migrations.AlterField(
            model_name='atividadeesportiva',
            name='id_professor',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='atividade_ministrado', to='pessoa.professor'),
        ),
    ]
