# Generated by Django 5.2.7 on 2025-10-29 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento',
            old_name='data',
            new_name='data_pagamento',
        ),
    ]
