# Generated by Django 5.2.7 on 2025-10-29 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0002_rename_data_pagamento_data_pagamento'),
        ('pessoa', '0005_administrador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='id_adm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_gerenciados', to='pessoa.administrador'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='tipo_pagamento',
            field=models.CharField(choices=[('MEN', 'Mensalidade'), ('DOA', 'Doação'), ('EVE', 'Evento'), ('OUT', 'Outro')], default='MEN', max_length=3, verbose_name='Tipo de Pagamento'),
        ),
    ]
