# Generated by Django 5.2.7 on 2025-10-30 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0003_pagamento_id_adm_pagamento_tipo_pagamento'),
        ('pessoa', '0006_remove_administrador_tel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('PG', 'Pago'), ('NP', 'Não Pago')], default='Não Pago', max_length=3, verbose_name='Status de Pagamento:'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='id_adm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_gerenciados', to='pessoa.administrador', verbose_name='Administrador'),
        ),
    ]
