# Generated by Django 5.2.7 on 2025-11-14 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0007_pagamento_id_aluno'),
        ('pessoa', '0011_doador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id_doacao', models.AutoField(primary_key=True, serialize=False)),
                ('id_doador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doacoes_feitas', to='pessoa.doador', verbose_name='Doador')),
            ],
        ),
    ]
