# Generated by Django 5.2.8 on 2025-11-26 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0011_doacao_data_doacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('RG', 'RG/CPF'), ('COMP', 'Comprovante de Residência'), ('MED', 'Atestado Médico'), ('CON', 'Contrato'), ('OUT', 'Outro')], default='OUT', max_length=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('arquivo', models.FileField(upload_to='uploads_documentos/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='meus_documentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
