<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-30 12:52
=======
# Generated by Django 5.2.7 on 2025-10-30 18:01
>>>>>>> a66c41c (Model de AtividadeEsportiva implementada)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0004_pagamento_status_alter_pagamento_id_adm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('PG', 'Pago'), ('NP', 'Não Pago')], default='NP', max_length=3, verbose_name='Status de Pagamento:'),
        ),
    ]
