# Generated by Django 5.2.7 on 2025-11-14 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0005_alter_pagamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
