# Generated by Django 5.2.7 on 2025-11-14 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0006_alter_pagamento_data_pagamento'),
        ('pessoa', '0010_alter_aluno_data_nasc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='id_aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aluno_pagante', to='pessoa.aluno', verbose_name='Aluno'),
        ),
    ]
