# Generated by Django 5.2.7 on 2025-11-14 18:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0008_doacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
