# Generated by Django 5.2.7 on 2025-11-14 18:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0010_alter_pagamento_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='data_doacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
